### ISSUE TITLE
Project Development is Slow

### ISSUE THREAD

**Issue by iamsoorena** [uber/react-digraph#103]
I think because of few number of people working on this project development is somehow slow.
I want to know what you think about future of this project?
Do you want to add other maintainers?
Do you want to make a discussion forum for this project?
I see a lot of potential and want to help anyway I can.

**Comment by iamsoorena** [comment]
To add more info on this topic I should say issue tracking for this project has some serious problems. :smiley:

**Comment by ajbogh** [comment]
Hi @iamsoorena. You're right about the slow development. Right now I'm the only developer on this project and I've recently been prioritized with new feature development on a different project. I will work with management so they're aware of your concerns so that we can add more maintainers and keep development up-to-speed.
