### ISSUE TITLE
maxTitleChars property is not being used

### ISSUE THREAD

**Issue by usernamedt** [uber/react-digraph#114]
For some reason the maxTitleChars logic seems to be missing from the current version of graph-view.js but it is stated as the property on the readme page.
It looks like that there was some functionality in the previous versions but now it's gone 
https://github.com/uber/react-digraph/blob/489226a1018a992e67ad7b90dcd97c8eb9f70049/src/components/graph-view.js

**Comment by ajbogh** [comment]
You're right, it looks as though this functionality was accidentally removed. Please feel free to create a PR to add it back. You can find the relevant code in node-text, and you will have to make sure to pass that property down from graph-view to node-text through the node component.

https://github.com/uber/react-digraph/blob/master/src/components/node-text.js

Alternatively, there's a callback function called `renderNodeText` in graph-view's props where you can return a JSX element with the proper text size. This function, if provided, will render the text rather than returning a NodeText component.

**Comment by thesuperhomie** [comment]
@usernamedt if you don't want to take this on, I'm happy to add it back :)

**Comment by usernamedt** [comment]
It would be great, I’ve got to pass exams atm, can’t help right now
