### ISSUE TITLE
Edge Calculation Question

### ISSUE THREAD

**Issue by amcdnl** [uber/react-digraph#132]
First off, great project! I've been going through the code and found some complex code around the edge layout. Could you explain what the purpose of these functions are?

https://github.com/uber/react-digraph/blob/master/src/components/edge.js#L127-L426

**Comment by ajbogh** [comment]
Absolutely! Edges are supposed to touch the nodes, but SVGs are incredibly difficult to get the intersections. When drawing an edge, the initial points are at the center of the nodes, not the sides, so we need to adjust the edge positions to handle this.

The original code only knew how to draw edges at circular offsets, so a square node would have an edge touching empty space above or beside it.

Each different node type (circle, square/rectangle/diamond, and polyline) requires a different collision detection algorithm. This allows the edge to touch the exact side of the visible node, depending on its type. We do a check using some CSS selectors to find out what the node type is, then send it through the correct algorithm. Each algorithm then uses various means to determine the true edge of the node.

The only caveat to this is that now nodes need to define the width and the height properties, which wasn't necessary before. This allows the edge calculation to understand the bounds of the SVG, which consists of a "window" (the SVG element - what the width and height defines) and a viewbox (zoom level). Most of the time the viewbox for nodes exactly equals the width and height properties. In order to calculate the edge offset we need to know the intersection point in relation to the node size in the graph.

Once we have the edge offsets, we move the beginning and end of the edge to the correct points (subtracting the size of the arrow as well) and make the edge look like it's touching the exact side of the node, no matter what shape we're displaying.

**Comment by amcdnl** [comment]
Thanks for the explanation!
