### ISSUE TITLE
Complex Node/Edge Circle Collision Bug

### ISSUE THREAD

**Issue by iChaosren** [uber/react-digraph#153]
**Describe the bug**
Error when trying to create an edge to a complex circle node.
This generally results in the entire browser freezing up soon after and a lot of errors being thrown in the console.

**To Reproduce**
1. Open up the example in this repo.
2. Add the below shape as a new node.
```
<symbol viewBox="0 0 100 100">
    <circle cx="50" cy="50" r="50" fill="transparent" stroke="transparent" />
    <circle cx="50" cy="50" r="34" />
    <path d="M50,0a50,50,0,1,0,50,50A50,50,0,0,0,50,0Zm0,90A40,40,0,1,1,90,50,40,40,0,0,1,50,90Z" />
</symbol>
```
3. Connect any other node to it or from it.
4. Check console for errors, attempt to move any node or create any other edge and watch it freeze up and become unresponsive.

**Expected behavior**
I expected it to detect the first circle in the symbol and use it for collision detection when creating an edge as it does if you for example remove the path and keep the two circles.

**Screenshots**
![image](https://user-images.githubusercontent.com/783885/62195553-8af2df00-b37c-11e9-9fc2-b07a604f6343.png)
![image](https://user-images.githubusercontent.com/783885/62195610-ab229e00-b37c-11e9-9f6c-5d128a818be8.png)

**Desktop:**
 - OS: Windows 10 64bit
 - Browser: Chrome
 - Version: Latest

**Additional context**
From what I can see, it allows multiple circle components, but as soon as I add any path at all, it breaks... Is there perhaps a way I can tell the collision detection to ignore the path element?

Without the path element:
![image](https://user-images.githubusercontent.com/783885/62196335-1caf1c00-b37e-11e9-9023-938d8064c2b4.png)

**Comment by ajbogh** [comment]
I can add some logic around your example to hopefully make it understand these complex nodes.

**Comment by ajbogh** [comment]
I've created a PR to address this issue: #157.

In this new code you can add a new property to the SVG nodes called `data-intersect-ignore`. This instructs the intersection selector to ignore these elements. 

The problem was that since the `path` element is selected before a `circle` in the intersection code, it would attempt to select your path even though you had a circle that would have been a better choice. Now we can specify which node is acceptable for selection. The code will still only select the first element it stumbles across, but at least now you can prevent it from using the wrong element.

const ComplexCircleShape = (
  <symbol viewBox="0 0 100 100" id="complexCircle" width="100" height="100">
    <circle cx="50" cy="50" r="50" fill="transparent" stroke="transparent" />
    <circle cx="50" cy="50" r="34" />
    <path
      d="M50,0a50,50,0,1,0,50,50A50,50,0,0,0,50,0Zm0,90A40,40,0,1,1,90,50,40,40,0,0,1,50,90Z"
      data-intersect-ignore="true"
    />
  </symbol>
);
```

I also attempted to make the path intersection more intelligent since your path is more complex than the simple paths that I had originally used when programming this code, however this will need additional work. Your path uses an 'a' between numbers and commas as separators. This isn't accounted for in the code. The best we can do right now is a simple poly shape, such as the one in the examples (`M 0 0 0 0Z`)

```
<path d="M 0 36 18 0 70 0 88 36 70 72 18 72Z" />
```

**Comment by iChaosren** [comment]
Awesome! Thanks!

I used Adobe Illustrator to design my nodes.
I'm personally not very familiar with the in's and out's of path elements.

I added the path you provided and it seems to be working quite well as an immediate solution:
![image](https://user-images.githubusercontent.com/783885/62350146-1c3f8e00-b502-11e9-9c17-cc400211f47d.png)

Thanks again!

**Comment by iChaosren** [comment]
Commit [1cdb07b](https://github.com/uber/react-digraph/commit/1cdb07b9120f7e2fa176da38cfc3189f53919614) Resolved the issue completely, Thanks!
