### ISSUE TITLE
SVG as NodeTypes

### ISSUE THREAD

**Issue by naumanzchaudhry** [uber/react-digraph#171]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Basically I am working on drag dropping svg elements onto graph canvas. And want to have that svg used as NodeType.

How can I accomplish that. Currently `NodeType` needs an object with `shape` `shapeId` and `typeText`

**Describe alternatives you've considered**
I am trying to import svg and using it as shape

```

import mySvgNodeA from "../assets/nodeA.svg;

export const NODE_A_TYPE = "nodeA";

NodeTypes: {
   nodeA: {
       shape : mySvgNodeA,
       shapeId: "#nodeA",
       typeText: "Node A"
  }
}

```
And then on my `onCreateNode` handler I am preparing the node like this for using NODE_A_TYPE
```
const viewNode = {
       id: Date.now(),
       title: payload.title,
       x,
       y,
       type: NODE_A_TYPE,
};     
```

**Comment by iChaosren** [comment]
According to React's own [documentation](https://create-react-app.dev/docs/adding-images-fonts-and-files) you're meant to do something more like this when adding files:

```jsx
import { ReactComponent as Logo } from './logo.svg';
const App = () => (
  <div>
    {/* Logo is an actual React component */}
    <Logo />
  </div>
);
```

More over, because of the way that `react-digraph` is designed, your SVGs are going to need at a bare minimum to conform to these simple rules:

1. The root component/element should always be of type `symbol`. Which has an almost identical implementation. 
i.e. 
```jsx 
<symbol viewBox="0 0 100 100" id="box"><rect width="100" height="100" /></symbol>
``` 
**As apposed to**
```jsx
<svg viewBox="0 0 100 100" id="box"><rect width="100" height="100" /></svg>
``` 

2. It needs to have a matching `id`... And that's all
