### ISSUE TITLE
How I can make curve line in this GraphView?

### ISSUE THREAD

**Issue by templar820** [uber/react-digraph#176]
I read about "getPathDescriptionStr" but didn't find access to it via GraphView interface. What should I write in <GraphView ..(?).. /> and what key combination to press to activate the build

**Comment by ajbogh** [comment]
Currently react-digraph doesn't support curved lines, however it was looked into briefly during the 5.0 refactor. We would be happy to accept PRs for edge-styles, or you can override edge rendering by using the afterRenderEdge attribute. This function is called immediately after the straight edge has been rendered. You can modify the edge in any way once this method is called. We render the initial edge because of the complex edge detection calculation needed to render edge arrows in the correct spots on different types of nodes.

**Comment by EfstathiadisD** [comment]
OK. Maybe I am not getting it, but how? This thing returns a string? What are you supposed to do with a freaking string? Let's say I want to draw my own path. How? I would need point (A, B => Their coordinates) in order to paint anything. Also, even if I force something into that function, it never appears. Can we have an example please? Some more docs? This should be re-opened. 
@ajbogh

**Comment by ajbogh** [comment]
We do not support drawing your own edges because the edge calculations are very difficult. They require both positions of the nodes, zoom level, some trigonometry, and intersection detection methods. We do, however, allow you to pass a function (afterRenderEdge) to be called after edges are rendered. You can then do whatever you want with that edge data.
