### ISSUE TITLE
Nodes do not re-render when prop gets updated

### ISSUE THREAD

**Issue by riccardolocci** [uber/react-digraph#192]
Hi, 
I'm trying to change the definition of the nodes passed to the `GraphView` each time a determined event occurs (in my case, when a value on a drop down list change).
However, the nodes involved in the update do not immediately change; to trigger a new rendering I have to hover over every node that I need to update.

Is there a way to force the rendering of updated nodes on a determined event?

**Comment by ajbogh** [comment]
Due to the rendering nature of react-digraph, and the responsibility to provide speed for rendering all nodes over flexibility for rendering a single node, you cannot modify a property of a node object and expect that node to re-render. If you want to re-render the node then you must create a new node array with the updated node. React-digraph will then loop through the entire array and determine which node has changed, then re-render that one node using an asynchronous rendering process.

```
oldNodesArray[5].someProp = "Test";
nodesArray = [...oldNodesArray];

...

<Graph
  nodes={nodesArray}
  ...
```

The following if statement checks if nodes are equal.

https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js#L344

**Comment by riccardolocci** [comment]
Unfortunately creating a new array each time I need an update did not work in my case.

However, thanks to the reference that you provided, I solved my issue by (ab)using the value `forceReRender` at line 274 (https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js#L274): every time I need a new render, I just pass a different value to `layoutEngineType`.

Thank you

**Comment by ajbogh** [comment]
I'm glad you could figure out a way around the issue. Feel free to contribute a PR with an adjustment if you feel like the code could be made better to suit your use case. Thanks!

**Comment by sillle14** [comment]
I also needed to force rerender nodes, and was able to solve the problem using a ref and directly calling `asyncRenderNode` as needed. Is this use case common enough that it would be worth adding this method to the docs in the Imperative API section?

**Comment by AhmadYoussef** [comment]
I faced the same problem and I was able to solve it by using a function from `ref` called `renderNodes() `
which will easily render all node but I don't know if it is a good idea to use it.

**Comment by ajbogh** [comment]
The graph-view class won't change its API, so you're safe to use renderNodes and asyncRenderNode as imperative functions. Please feel free to include the documentation in the README with a PR.
