### ISSUE TITLE
Weird behaviour with onSelectNode

### ISSUE THREAD

**Issue by sikula** [uber/react-digraph#193]
**Describe the bug**
onSelectNode appears to be called not only when a node is selected, but even clicking on the background (or any mouseUp action).

**Expected behavior**
onSelectNode only called when a node is clicked

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Additional context**
[This CodeSandbox](https://codesandbox.io/s/react-digraph-dkvjy?from-embed) has the same issue

**Comment by ajbogh** [comment]
This is expected behavior. When a node is selected the onSelectNode function will receive an INode object, when the background is clicked the argument will be `null`. When the argument is null the website's selectedNode state should be cleared, which will allow react-digraph to render the graph with no nodes selected.
