### ISSUE TITLE
querySelector fails with IDs with slashes

### ISSUE THREAD

**Issue by timhwang21** [uber/react-digraph#201]
**Describe the bug**
Operations like `panToNode` fail when the ID has special characters like slashes in them.

**To Reproduce**
1. Set `someNode[nodeKey]` to be `test/slash` or something
2. Call `panToNode`
3. See error

**Expected behavior**
`querySelector` doesn't error

**Additional context**
While IMO the most correct fix is to call `CSS.escape()` like `this.entities.querySelector(`#node-${CSS.escape(id)}-container`);`, this doesn't have the best browser support. [Here is a somewhat old polyfill.](https://github.com/mathiasbynens/CSS.escape)

Annoyingly, we would have to update every instance of `node[nodeKey]`. (It might be good to note somewhere that users need to escape their IDs if they use any API that uses `querySelector`?)

Alternatlvely, I think it would be great to have an alternate API to `props.nodeKey` that's something like `props.getID` that looks like `getID: (node: INode) => string`. So we can do the following:

```tsx
// before
<GraphView nodeKey="name"/>

// after
<GraphView nodeKey={node => myPreprocessFunction(node.name)}
```

**Comment by ajbogh** [comment]
Thank you for the report @timhwang21. If you are interested, please feel free to create a PR that's backwards compatible for the users, if possible. 

An idea regarding the CSS.escape, it appears to work in most modern browsers. We can assume that it'll work on Edge now too since it's being shipped with Blink, the Chrome rendering engine. A safety mechanism we should employ, if we're concerned with support, is to wrap it in a function that checks  for the existence of CSS.escape before returning the resulting string, otherwise we should return the  original unescaped string. Users of old browsers will get the same broken experience, and workflow developers will need to support them by escaping the strings themselves, but newer browsers will be fine.

Using your code:

```
function escapeCSS(cssSelectorText) {
  return CSS.escape ? CSS.escape(cssSelectorText) : cssSelectorText; 
}

this.entities.querySelector(#node-${escapeCSS(id)}-container);
```

**Comment by timhwang21** [comment]
Thanks for the response! After working with the library a bit more, I feel getter props would be a more generic solution for this problem, as well as several others I encountered.

Specifically, I noticed that the key `type` is hardcoded as the node type; however `type` is an existing key in my data. Right now I am avoiding this by preprocessing my data, but the consequences is I have to post process to get it to the correct shape, which is error prone and frustrating. My proposal would be to deprecate the `nodeKey` prop and instead provide `getID`, `getType`, etc. props.

To me this concisely solves both problems: I can pass `getID={node => CSS.escape(node.id)}` etc. Default props can be provided to preserve existing behavior.

Would love to hear your thoughts and happy to work on a PR for whatever solution is best.

**Comment by ajbogh** [comment]
That's a possible solution. For backwards compatibility you could detect if getID is defined and use it, or fall back to nodeKey. The concern I have it needing to provide getters for every current and future property we might use. 

We've had good luck processing an object of nodes into the necessary array with the react-digraph properties, possibly assigning the original node to a property of the new react-digraph node, or using the selection to modify the original node shape in the datastore. Rather than making the react-digraph nodes be exactly the same as the original, instead consider them as references to the originals. The only downside to this is that each time the node list changes the node array has to be re-generated.

```
const originalNodes = {
  testID: {
    id: 'testID',
    someData: 'here',
    nodeMeta: { x: 10, y: 0 }
  },
  otherID: {
    id: 'otherID',
    someData: 'here',
    nodeMeta: { x: 0, y: 10 }
  }
};

// the above object is converted to the below array with the necessary react-digraph properties.
// conversion happens on re-renders due to data changing from user interaction.

const reactDigraphNodes = [
  { x: 10, y: 0, id: 'testID' },
  { x: 0, y: 10, id: 'otherID' }
];
```

**Comment by timhwang21** [comment]
Yep, that is my current solution as well. It works fine, the main annoyance is that I now need two sets of slightly different utility functions (for the mapped and unmapped version of the nodes), because in my UI the user can make changes both in the graph canvas and externally.

In this case maybe the right thing to do would be to file a documentation PR? Would be happy to do so.
