### ISSUE TITLE
Implement Complex Text Nodes in an Example

### ISSUE THREAD

**Issue by gamedevjoey** [uber/react-digraph#217]
Hello, I recently found your tool and decided to add a more complex system for rendering text on the node.  My tool uses draft.js to create a complex text editor which can be used to create text nodes with complex attributes like bold, italics, colors, and even images.  My code has been tested and thoroughly documented: https://codesandbox.io/s/react-digraph-textboxes-6e998

I was wondering if you could look over my code over and add it to one of your examples.  I have specific instructions for migrating the project as well as a full feature list.  If not that's ok but I think it would be a very useful attention and would better show the ability of your tool of you put in a demo.

**Comment by ajbogh** [comment]
Thanks for creating this issue. We appreciate the new ideas regarding usability. This particular feature looks more like an addition on top of the base functionality rather than something that should be incorporated into the base functionality and examples. As a developer of your own website, you can choose any method of creating new nodes and edges, and we provide rendering method overrides that allow you to create custom SVG elements on edges and nodes in whatever way you like. Every developer may choose to use some new and interesting way to add nodes and edges, or render them, and that's what makes this system so dynamic, but it would be impossible to create a new example for every method.

Creating issues like this, even if they're closed, allows others to see your example in codesandbox  (or screenshots), and gain new ideas. Please feel free to add screenshots or create a blog post showcasing your own investigation and development with react-digraph.

**Comment by gamedevjoey** [comment]
Alright I will do that.  Thanks for the fast responce.  If anyone else wants to use the project I have attached some screenshots as well as a link to the sandbox:

This app builds on the React-Digraph framework by adding a new type of node called a "textbox". A textbox can contain complex text data including bold text, italics, custom font sizes, colors, emojis and even images. A textbox contains text information stored in its title as html code which is run with the node. To create a textbox the user uses a user friendly text editer for creating complex text data. The text editer can be toggled on and off from top of the screen for better visibility. Forthermore, the textbox node is a custom type node which is fully intrigated into the Digraph framework. All textbox nodes can be moved, and delated as part of the graph, and all textbox nodes and their html data is stored in the graph. A textbox can be stored in a node array with no additinal props as all the text data is stored inside "title".

<img width="827" alt="Screen Shot 2020-05-03 at 1 54 06 PM" src="https://user-images.githubusercontent.com/64991917/81408117-a7d9f100-910a-11ea-8647-2c0856b8e664.png">
<img width="704" alt="Screen Shot 2020-05-08 at 9 07 46 AM" src="https://user-images.githubusercontent.com/64991917/81408485-4fefba00-910b-11ea-9543-404f841054db.png">


Sandbox: https://codesandbox.io/s/react-digraph-textboxes-6e998
