### ISSUE TITLE
Use Route Link inside a custom componentNode

### ISSUE THREAD

**Issue by EfstathiadisD** [uber/react-digraph#229]
**Describe the bug**
I am trying to incorporate a Custom Component Node(Pure JSX), with `foreignObject`. In one of the Components, i have a Link. Regular `react-router-dom` Link. And I see this error:
```
Uncaught Error: Invariant failed: You should not use <Link> outside a <Router>.
```
At this point the graph(Elements), with all nodes and edges disappear.

**To Reproduce**
I don't have steps to reproduce right now. I cannot share my code, but I will make a `CodeSandbox` example later on.

**Expected behavior**
I would really like to know, what the actual problem is here. I basically have a custom Node, with a Link inside, and the whole graph doesn't get painted.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Edge(Chromium) and Firefox]
 - Version [83.0.478]

**Comment by ajbogh** [comment]
I recommend using a hyperlink <a> element rather than a <Link> element if you can't find a solution.

You may have already researched the error and found the link below, but I wanted to suggest that it may be the structure of the Router in your code, rather than a react-digraph error. Perhaps you can add a <Link> element next to the <Graph> element and see if it still has the same warning. That would inform you if it's the Graph that's producing the error or the parent component itself. Without knowing more about your app structure and route definitions, the hyperlink suggestion is likely the easiest solution.

https://stackoverflow.com/questions/48640280/you-should-not-use-link-outside-a-router

**Comment by EfstathiadisD** [comment]
Thanks for the answer. The problem isn't with the Application I am afraid. Links work perfectly outside of the Digraph. And while I have switch to an `<a />` Tag, it doesn't work, on the left click. Only right click and new window works. Will take a look on how to fix it and post the solution. Leaving the issue open until then.
