### ISSUE TITLE
onDeleteNode is not working in Firefox

### ISSUE THREAD

**Issue by AhmadYoussef** [uber/react-digraph#240]
**Describe the bug**
I am trying to delete a node in Firefox but it didn't trigger function onDeleteNode  or canDeleteNode 
it is working perfectly on Chrome. 

**Desktop (please complete the following information):**
 - Browser  Firefox
 - Version [78.0.2]

**Additional context**
any idea how can I solve the problem

**Comment by mosofsky** [comment]
Neither `onDeleteNode` nor `onDeleteEdge` are working for me.

Desktop:
OS: Mac
Browser: Chrome
Version: "react-digraph": "^6.7.1"

I cloned react-digraph and by experimentation I found a way to make it work.  Instead of subscribing the keydown listener to `this.viewWrapper.current`, subscribe it instead to `document`.

To be clear, I changed the following code:

```
      this.viewWrapper.current.addEventListener(
        'keydown',
        this.handleWrapperKeydown
      );
```

source: https://github.com/uber/react-digraph/blob/3f853af3d427eafd8d944025e93c66a97c9afc4e/src/components/graph-view.js#L191

I changed that code to this:

```
      document.addEventListener(
        'keydown',
        this.handleWrapperKeydown
      );
```

Now the `onDeleteNode` nor `onDeleteEdge` work as expected.

I'm knew to this project and not deeply knowledgable about JavaScript so I'm not sure if I should submit a pull request.  Would anyone more expert in this be able to explain why attaching the listener to `document` works but the existing code does not?  If it's an acceptable solution, could you possibly fix it or support me in submitting a pull request?

Thank you in advance!

**Comment by AhmadYoussef** [comment]
@ajbogh, could you support us here?

**Comment by ajbogh** [comment]
Thanks for the report. I'm looking into this issue now. This one's difficult because in order to support multiple graphs on one page we need to target the viewWrapper for events, however the viewWrapper doesn't handle the keydown events.

When we capture the document keydown event it doesn't report the element that was last focused, so now in order to know which graph we're editing we need to determine which one is actively in focus. This is relatively easy to accomplish with onFocus and onBlur events, but it adds another state property. I will need to test this change a little more.

**Comment by AhmadYoussef** [comment]
Thanks for your replay.  I am actually facing another problem with firefox ... when I wanna create a new edge between a normal node and complex shape node.

For Example, when I am trying to connect node F(5) with ( node G(8) or loop), I need to repeat createEdge action twice or more, and most of the time, this problem happened when the target is a complex shape node.

but in chrome, it works perfectly.
I don't know if I am doing something wrong or perhaps there is a bug here

![Bildschirmfoto 2020-08-05 um 10 55 31](https://user-images.githubusercontent.com/5328749/89392816-5097ec80-d70a-11ea-8b94-f7cbdc41063d.png)

**Comment by ajbogh** [comment]
@AhmadYoussef please report that issue as a separate issue.

**Comment by ajbogh** [comment]
@AhmadYoussef  Here's a PR for your review (#246). I will have others review it as well.

**Comment by mosofsky** [comment]
Thank you so much for fixing this @ajbogh .  I was able to confirm the fix on the examples packaged with the react-digraph repository on its master branch.

However, when I upgraded my project to react-digraph 7.0.0, I was still not able to delete nodes nor edges.  I am pretty sure your fix is in 7.0.0 according to the CHANGELOG.md but the behavior is exactly the same for me as with 6.7.1.

1. `onDeleteNode` gets called but `selected` and `nodeId` are `undefined`.  The `nodes` array contains the nodes prior to the deletion, as expected.  But if I don't know the `selected` nor `nodeId`, I can't filter out the deleted node.

2. When I try to delete an edge, `onDeleteEdge` does not get called but for some reason `onDeleteNode` does get called.  The values passed to `onDeleteNode` are the same as above, not that it matters because it's the wrong function to get a callback.  I can confirm that I have, indeed, passed 

``` lang-typescript
                      <GraphView ref='GraphView'
                               nodeKey={NODE_KEY}
                               nodes={nodes}
                               edges={edges}
                               selected={selected}
                               nodeTypes={NodeTypes}
                               nodeSubtypes={NodeSubtypes}
                               edgeTypes={EdgeTypes}
                               onSelectNode={onSelectNode}
                               onCreateNode={onCreateNode}
                               onUpdateNode={onUpdateNode}
                               onDeleteNode={onDeleteNode}
                               onSelectEdge={onSelectEdge}
                               onCreateEdge={onCreateEdge}
                               onSwapEdge={onSwapEdge}
                               onDeleteEdge={onDeleteEdge}/>
```

Here are the relevant functions:

``` lang-typescript
        const onDeleteNode = (selected: INode, nodeId: string, oldNodes: INode[]) => {
            console.log("onDeleteNode selected=|" + JSON.stringify(selected) + "| nodeId=|" + nodeId + "|");

            console.log("onDeleteNode before |" + JSON.stringify(oldNodes) + "|");

            const newNodes = oldNodes.filter((node, _i) => {
                return (selected.id !== node.id);
            });

            console.log("onDeleteNode after |" + JSON.stringify(newNodes) + "|");

            this.props.saveBOM(newNodes, this.props.data.edges);
        };
```

``` lang-typescript
        const onDeleteEdge = (selectedEdge: IEdge, edges: IEdge[]) => {
            console.log("onDeleteEdge before |" + edges + "|");

            const newEdges = edges.filter((edge, _i) => {
                return (
                    selectedEdge !== edge
                );
            });

            console.log("onDeleteEdge after |" + edges + "|");

            this.props.saveBOM(this.props.data.nodes, newEdges);
        };
```

Here's the output in the logs when I try to delete a node:

```
onDeleteNode selected=|{}| nodeId=|undefined|
onDeleteNode before |[{"id":1,"title":"FDP","x":258,"y":50,"type":"empty"},{"id":2,"title":"DP","x":258,"y":250,"type":"empty"},{"id":3,"title":"API","x":258,"y":450,"type":"empty"}]|
onDeleteNode after |[{"id":1,"title":"FDP","x":258,"y":50,"type":"empty"},{"id":2,"title":"DP","x":258,"y":250,"type":"empty"},{"id":3,"title":"API","x":258,"y":450,"type":"empty"}]|
```

And when I try to delete an edge, I get the exact same logs.  To be clear, the `onDeleteEdge` logs are not printed, instead the `onDeleteNode` logs are printed.

I can try to reproduce this on the examples but if you have any suggestions on what I might try to change in my project, I would love your input.  For example, have I defined my nodes incorrectly somehow?  They do render, so I think they're fine but maybe you see something I did wrong.

And if you think I should file this as a new issue, just let me know.

Thanks in advance!

**Comment by AhmadYoussef** [comment]
well, I will tell you how acutely I did it. 
At the beginning a noticed that the library changing my state directly ... I don't know maybe they didn't do a copy of my nodeList .... so I decided to create initialNodes and initialEdges so I didn't use oldNodes that function offer. 
so I just did a filter as you did then I saved the new array in my state

```
    const onDeleteNode = (selected, nodeId, nodesList) => {
        console.log(nodesList);
        const copyNodeList = cloneDeep(initialNodes);
        const copyEdgeList = cloneDeep(initialEdges);
        const obj = deleteSelectedElement(copyNodeList, copyEdgeList, selected); // i am just don't getting the edges that is connected to this node to delete it too

        updateUndoItems();
        setNodes(cloneDeep(obj.nodes));
        setEdges(cloneDeep(obj.edges));
        setInitialNodes(cloneDeep(obj.nodes));
        setInitialEdges(cloneDeep(obj.edges));
        setSelected(null);

    };
```

**Comment by AhmadYoussef** [comment]
if you wanna have more control on your code you can use a key called selected
```

 <GraphView ref='GraphView'
                               nodeKey={NODE_KEY}
                               selected={selected} // default value is true ... and you can give it an object 
                               nodes={nodes}
                               edges={edges}
                               selected={selected}
                               nodeTypes={NodeTypes}
                               nodeSubtypes={NodeSubtypes}
                               edgeTypes={EdgeTypes}
                               onSelectNode={onSelectNode}
                               onCreateNode={onCreateNode}
                               onUpdateNode={onUpdateNode}
                               onDeleteNode={onDeleteNode}
                               onSelectEdge={onSelectEdge}
                               onCreateEdge={onCreateEdge}
                               onSwapEdge={onSwapEdge}
                               onDeleteEdge={onDeleteEdge}/>
```

The selected key has default value is true ... but you can use it as an object.
so when you trigger onSelectNode you will receiver node ... so you can save it in the state and give it back to Selected.. in this way, you will be sure that the selected node is saved in your state ... and you can use this variable when onDeleteNode is triggered 

you can find an example [here](https://github.com/uber/react-digraph/blob/9ccbe92ce22ca4336fdbbca034d21e87b43bd50c/src/examples/graph.js#L541)

**Comment by ajbogh** [comment]
@mosofsky Thanks for asking about the deleteNode function. Our example code is a little different than yours.

```
  // Deletes a node from the graph
  onDeleteNode = (viewNode: INode, nodeId: string, nodeArr: INode[]) => {
    const graph = this.state.graph;
    // Delete any connected edges
    const newEdges = graph.edges.filter((edge, i) => {
      return (
        edge.source !== viewNode[NODE_KEY] && edge.target !== viewNode[NODE_KEY]
      );
    });

    graph.nodes = nodeArr;
    graph.edges = newEdges;

    this.setState({ graph, selected: null });
  };
```

Notice that we're storing the graph in the state.

Regarding the code directly modifying the arrays, this is a legacy issue that was inherited from the 4.x code. It enables faster rendering because we don't have to create new arrays at every modification, but it does create some confusing experiences for the developer. I am planning on rewriting react-digraph to use hooks in the near future, so I will investigate copying the nodes into a new array during modifications. The challenge is to make sure it's fast for 1000+ nodes.

**Comment by mosofsky** [comment]
@ajbogh thank you for the detailed reply.  I see that your `onDeleteNode` function depends on receiving a value for `viewNode` so that you can remove edges connected to the node being deleted.  The problem I'm facing is that I receive an **empty object** for `viewNode`.

The second problem I'm facing is `onDeleteEdge` does not get triggered; instead `onDeleteNode` for some reason is triggered when I select an edge and press the delete button.  In my use case, I need to be able to delete an edge between two nodes.  I need `onDeleteEdge` to be called instead of `onDeleteNode`.

I really appreciate your help, this is great library you've made.  Getting these two delete issues resolved is what's blocking successful integration on the project I'm working on.

**Comment by mosofsky** [comment]
Update: I've got node deletion working but not edge deletion.  `onDeleteEdge` simply isn't called.

To fix node deletion I discovered I had to move my functions so they're not `const` in the `render` but rather they're functions on the component.

I changed from this:

``` lang-typescript
class Home extends Component<HomeProps, HomeLocalState> {
   // ...
   render() {
        const onDeleteNode = (_selected: INode, nodeId: string, oldNodes: INode[]) => {
             // ...
        }
    }
}
```

To this:

``` lang-typescript
class Home extends Component<HomeProps, HomeLocalState> {
   // ...
   onDeleteNode = (selected: INode, nodeId: string, oldNodes: INode[]) => {
             // ... now selected and nodeId contain valid values
   }
   render() {
        // ... 
    }
}
```

**Comment by mosofsky** [comment]
I got edge deletion working, finally.  After debugging the react-digraph code with my own console.log() statements in my application, I found the root cause was my incorrect usage of the `selected` property on `GraphView`.  I figured out that `selected`'s possible values are `null` | `INode` | `IEdge`.  However, in my own code I've separated these because they don't have the same type (I'm using TypeScript).

Here's how my state is defined:

``` lang-typescript
interface HomeLocalState {
    // ...
    selectedNode: INode | null,
    selectedEdge: IEdge | null
}
```

To fix the problem, when `render()` returns the `GraphView`, I now set `selected` by calling a function, `getSelectedNodeOrEdge()` that figures out whether to pass `selectedNode`, `selectedEdge`, or `null`:

``` lang-typescript
                    <GraphView ref='GraphView'
                               nodeKey={NODE_KEY}
                               nodes={this.props.data.nodes}
                               edges={this.props.data.edges}
                               selected={getSelectedNodeOrEdge(this.state)}
                               nodeTypes={this.NodeTypes}
                               nodeSubtypes={this.NodeSubtypes}
                               edgeTypes={this.EdgeTypes}
                               onSelectNode={this.onSelectNode}
                               onCreateNode={this.onCreateNode}
                               onUpdateNode={this.onUpdateNode}
                               onDeleteNode={this.onDeleteNode}
                               onSelectEdge={this.onSelectEdge}
                               onCreateEdge={this.onCreateEdge}
                               onSwapEdge={this.onSwapEdge}
                               onDeleteEdge={this.onDeleteEdge}/>
```

Here's how `getSelectedNodeOrEdge` decides which one:

``` lang-typescript
function getSelectedNodeOrEdge(state: Readonly<HomeLocalState>): INode | IEdge | null {
    const selectedNode = state.selectedNode;
    const selectedEdge = state.selectedEdge;
    
    let selectedNodeOrEdge: INode | IEdge | null;
    
    if (null !== selectedNode && null !== selectedEdge) {
        throw Error("A node and an edge should not be selected at the same time");
    } else if (null !== selectedNode) {
        selectedNodeOrEdge = selectedNode;
    } else if (null !== selectedEdge) {
        selectedNodeOrEdge = selectedEdge;
    } else {
        selectedNodeOrEdge = null;
    }

    return selectedNodeOrEdge;
}
```

Here's how my code guarantees only one of these values is set:

``` lang-typescript
    onSelectNode = (node: INode | null) => {
        this.setState({...this.state, selectedNode: node, selectedEdge: null});
    };

    onSelectEdge = (selectedEdge: IEdge) => {
        this.setState({...this.state, selectedEdge: selectedEdge, selectedNode: null});
    };

    onDeleteNode = (selectedNode: INode, nodeId: string, oldNodes: INode[]) => {
        // ... node deletion code omitted for brevity ...

        this.setState({...this.state, selectedNode: null});
    };

    onDeleteEdge = (selectedEdge: IEdge, edges: IEdge[]) => {
        // ... edge deletion code omitted for brevity ...

        this.setState({...this.state, selectedEdge: null});
    };
```

I suggest changing the type of `selected` in `IGraphViewProps` to `selected?: null | INode | IEdge` and consider changing its name to `selectedNodeOrEdge` to make it clearer.

Thank you @ajbogh and @AhmadYoussef for your input, feedback, and fixes.  It all helped.

**Comment by ajbogh** [comment]
Thanks for the detailed code. I will consider changing the "selected" property to "selectedNodeOrEdge" for clarity in the next release. You're right that "selected" can be confusing. This is a holdover from the 4.0 days, but we have the opportunity to improve the code now.

I'm currently refactoring everything to use hooks, which will be a minor update to the 7.0.0 branch, so I will consider deprecating the "selected" field in the upcoming releases.

**Comment by ajbogh** [comment]
@mosofsky, please see #250
