### ISSUE TITLE
INode, IEdge

### ISSUE THREAD

**Issue by maheshdeploy** [uber/react-digraph#249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi, Is it possible to have some implementation like  INode,  IEdge, and creating a new node inside of Canvas,  on a story book.

**Comment by ajbogh** [comment]
There is an examples folder under src that includes several examples of nodes and edges, and methods of creating new nodes and edges. The typings folder also includes Typescript types for INode and IEdge.

For the moment we have decided against storybook due to the complexity of react-digraph and the already available examples.
