### ISSUE TITLE
Export Graph

### ISSUE THREAD

**Issue by Malikx-Alee** [uber/react-digraph#253]
I couldn't find any option in react-digraph to export the graph in multiple graph format like GEXF or GraphML. It would be great if its added in the library. If it exists then correct me.

**Comment by thinkty** [comment]
I'm not really familiar with GEXF or GraphML, but after taking a look at the file format ([GEXF](https://gephi.org/gexf/format/), [GraphML](http://graphml.graphdrawing.org/primer/graphml-primer.html#GraphGraph)), I think one can convert (parse) from JSON to a GEXF or GraphML format.

**Comment by ajbogh** [comment]
This is more of the website's job rather than react-digraph's job. The digraph is really just the canvas for displaying your website's data, which is passed to it in 2 arrays (may change in the future). Your website controls the source of the data and the format, so you can convert the website data from any JSON format to any other JSON format, and provide buttons to export the graph.

This is somewhat similar to what react-digraph provides with the Transformer classes. You can create your own transformer that converts a data format to the react-digraph node and edge arrays, similarly you can add a method to un-convert from react-digraph to the original format. These transformer classes don't need to be within the react-digraph codebase, you can create your own and use it the same, but [we do include one as an example](https://github.com/uber/react-digraph/tree/master/src/utilities/transformers).

**Comment by Malikx-Alee** [comment]
@thinkty  @ajbogh  Thank you for guiding me. You are right these should be the feature of the website as it manages data.
