### ISSUE TITLE
feat-req: Node range selection using drag

### ISSUE THREAD

**Issue by kfern** [uber/react-digraph#304]
I would like to make a node range selection using drag. How can I do it?

Can be adapted something like https://gist.github.com/paradite/71869a0f30592ade5246/ ? 

Salu2
Fernando

**Comment by ajbogh** [comment]
React-digraph v8.0.0 will include multi-selection using Ctrl-Shift-Drag, however it will also require a code change. I'm currently working on the code which involves removing and refactoring the deprecated methods and variables. You can see the progress in v8.0.0-alpha.1, however this code is not recommended for use because it's in a broken state. Please wait until the 8.0.0 version.

**Comment by kfern** [comment]
@ajbogh: I am using the tests to learn how it could be done. I'm adding tests to handleMultipleSelected and findNodesWithinArea. 
WIP https://github.com/uber/react-digraph/pull/305

Can I help you?

**Comment by ajbogh** [comment]
Thanks for the PR! 

There is a great amount of change happening in the graph-view.js file at the moment so I would hold off on additional tests until the 8.0.0-alpha.2 gets merged. The main changes are the selectedNodes, selectedEdges, onSelectNodes, and onSelectEdges properties are going away and some of the other functions (onPasteSelected for example) are being changed to take the new `selected` property now.
