### ISSUE TITLE
Add async option for onCreateNode and onCreateEdge

### ISSUE THREAD

**Issue by iamsoorena** [uber/react-digraph#96]
**Is your feature request related to a problem? Please describe.**
Currently, `onCreateNode` function does not return any promise.
Consider the case when I want to be able to add a node only when a promise is resolved from my side.
For example I want to add a node only when user provided an input for it's name.
what should I do?
I don't think It's possible now.
I was able to make this thing work in version 4 forking the repo, but this feature is not available not in v4 neither in v5.

**Describe the solution you'd like**
I think we can add a separate prop named `onCreateNodeAsync` and check out It's availability in `handleSvgClicked` function.

**Comment by ajbogh** [comment]
For background, the `onCreateNode` callback function is called from `handleSvgClicked` synchronously. The responsibility is on the parent website on how a node is created, or whether it's created at all.

Your onCreateNode implementation only has to add a new node to an array and call setState() so that the graph is updated, how you get to that point (synchronously or asynchronously) is up to you.

In an implementation that I maintain, the onCreateNode function is a simple wrapper that first checks if nodes are allowed to be created, then it calls an API to create the node. When the API responds with success then we refresh the graph with setState(). This is all asynchronous, so I think it would solve your problem.

react-digraph call:
```
if (!this.props.readOnly && d3.event.shiftKey) {
  const xycoords = d3.mouse(d3.event.target);
  this.props.onCreateNode(xycoords[0], xycoords[1]);
}
```

External website implementation example:
```
async onCreateNode(x, y) {
    // fancy await example could instead be a promise with .then().
    const newNode = await myAPI.createNode({
      x, 
      y,
      authorId: theBrowserUser,
      otherMeta: {}
    });
    
    // update your node list
    nodes = [
      newNode,
      ...this.state.nodes
    ];

    // forces the graph to re-render the nodes
    this.setState({
      nodes
    });
}
```
